# Spark Core
spark.master                        spark://172.22.0.4:7077
spark.serializer                    org.apache.spark.serializer.KryoSerializer
spark.sql.warehouse.dir             hdfs://172.22.0.2:9000/user/hive/warehouse
spark.sql.adaptive.enabled          true
spark.eventLog.enabled              false

# Memory Configuration
spark.driver.memory                 1g
spark.executor.memory               1g
spark.executor.cores                1

# MinIO/S3 Configuration
spark.hadoop.fs.s3a.endpoint                            http://shminio:9302
spark.hadoop.fs.s3a.access.key                          minioadmin
spark.hadoop.fs.s3a.secret.key                          minioadmin
spark.hadoop.fs.s3a.impl                                org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.path.style.access                   true
spark.hadoop.fs.s3a.connection.ssl.enabled              false
spark.hadoop.fs.s3a.aws.credentials.provider            org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
spark.hadoop.fs.s3a.connection.maximum                  15
spark.hadoop.fs.s3a.fast.upload                         true
spark.hadoop.fs.s3a.fast.upload.buffer                  disk
spark.hadoop.fs.s3a.multipart.size                      64M
spark.hadoop.fs.s3a.multipart.threshold                 64M

# Hadoop Configuration
spark.hadoop.fs.defaultFS                                hdfs://172.22.0.2:9000
spark.hadoop.dfs.namenode.rpc-address                    172.22.0.2:9000

# Driver Configuration
spark.driver.bindAddress                                 0.0.0.0
spark.ui.bindAddress                                     0.0.0.0
spark.driver.host                                        shjupyter
#spark.driver.host                                        localhost